-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-09 10:54:51 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE TB_CARTEIRA 
    ( 
     carteira_id      INTEGER  NOT NULL , 
     saldo_mobilidade NUMBER (6,2)  NOT NULL , 
     usuario_id       INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_CARTEIRA 
    ADD CONSTRAINT TB_CARTEIRA_PK PRIMARY KEY ( carteira_id ) ;

ALTER TABLE TB_CARTEIRA 
    ADD CONSTRAINT TB_CARTEIRA_usuario_id_UN UNIQUE ( usuario_id ) ;

CREATE TABLE TB_COMPROVANTE 
    ( 
     comprovante_id   INTEGER  NOT NULL , 
     arquivo          BLOB  NOT NULL , 
     data_envio       DATE  NOT NULL , 
     status_validacao VARCHAR2 (50) DEFAULT 'PENDENTE'  NOT NULL , 
     data_validacao   DATE , 
     usuario_id       INTEGER  NOT NULL , 
     missao_id        INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_COMPROVANTE 
    ADD 
    CHECK (status_validacao IN ('APROVADO', 'PENDENTE', 'REPROVADO')) 
;

ALTER TABLE TB_COMPROVANTE 
    ADD CONSTRAINT TB_COMPROVANTE_PK PRIMARY KEY ( comprovante_id ) ;

ALTER TABLE TB_COMPROVANTE 
    ADD CONSTRAINT TB_COMPROVANTE_USU_MIS_UN UNIQUE ( usuario_id , missao_id ) ;

CREATE TABLE TB_CONQUISTA 
    ( 
     conquista_id INTEGER  NOT NULL , 
     nome         VARCHAR2 (150)  NOT NULL , 
     descricao    VARCHAR2 (200)  NOT NULL 
    ) 
;

ALTER TABLE TB_CONQUISTA 
    ADD CONSTRAINT TB_CONQUISTA_PK PRIMARY KEY ( conquista_id ) ;

CREATE TABLE TB_MISSAO 
    ( 
     missao_id     INTEGER  NOT NULL , 
     titulo        VARCHAR2 (150)  NOT NULL , 
     tipo_missao   VARCHAR2 (30)  NOT NULL , 
     descricao     VARCHAR2 (150)  NOT NULL , 
     pontos_missao INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_MISSAO 
    ADD CONSTRAINT TB_MISSAO_PK PRIMARY KEY ( missao_id ) ;

CREATE TABLE TB_PONTOS 
    ( 
     pontos_id        INTEGER  NOT NULL , 
     usuario_id       INTEGER  NOT NULL , 
     origem           VARCHAR2 (30)  NOT NULL , 
     creditos_gerados NUMBER (6,2)  NOT NULL , 
     data_pontuacao   DATE  NOT NULL , 
     pontos_gerados   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_PONTOS 
    ADD CONSTRAINT TB_PONTOS_PK PRIMARY KEY ( pontos_id ) ;

CREATE TABLE TB_RECARGA 
    ( 
     recarga_id       INTEGER  NOT NULL , 
     valor_recarga    NUMBER (6,2)  NOT NULL , 
     codigo_barras    VARCHAR2 (100)  NOT NULL , 
     status_recarga   VARCHAR2 (30)  NOT NULL , 
     data_solicitacao DATE  NOT NULL , 
     data_pagamento   DATE , 
     data_credito     DATE , 
     usuario_id       INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_RECARGA 
    ADD 
    CHECK (valor_recarga BETWEEN 10 AND 200) 
;

ALTER TABLE TB_RECARGA 
    ADD 
    CHECK (status_recarga IN ('creditado', 'pendente', 'recusado')) 
;

ALTER TABLE TB_RECARGA 
    ADD CONSTRAINT TB_RECARGA_PK PRIMARY KEY ( recarga_id ) ;

CREATE TABLE TB_USUARIO 
    ( 
     usuario_id    INTEGER  NOT NULL , 
     nome          VARCHAR2 (150)  NOT NULL , 
     pontos        INTEGER DEFAULT 0  NOT NULL , 
     email         VARCHAR2 (150)  NOT NULL , 
     data_cadastro DATE  NOT NULL 
    ) 
;

ALTER TABLE TB_USUARIO 
    ADD CONSTRAINT TB_USUARIO_PK PRIMARY KEY ( usuario_id ) ;

ALTER TABLE TB_USUARIO 
    ADD CONSTRAINT TB_USUARIO_email_UN UNIQUE ( email ) ;

CREATE TABLE TB_USUARIO_CONQUISTA 
    ( 
     data_conquista DATE  NOT NULL , 
     usuario_id     INTEGER  NOT NULL , 
     conquista_id   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_USUARIO_CONQUISTA 
    ADD CONSTRAINT TB_USUARIO_CONQUISTA_PK PRIMARY KEY ( usuario_id, conquista_id ) ;

CREATE TABLE TB_USUARIO_MISSAO 
    ( 
     data_cumprimento   DATE  NOT NULL , 
     status_missao      VARCHAR2 (30)  NOT NULL , 
     pontuacao_recebida INTEGER  NOT NULL , 
     usuario_id         INTEGER  NOT NULL , 
     missao_id          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_USUARIO_MISSAO 
    ADD 
    CHECK (status_missao IN ('cancelada', 'concluida', 'em_andamento', 'pendente')) 
;

ALTER TABLE TB_USUARIO_MISSAO 
    ADD CONSTRAINT TB_USUARIO_MISSAO_UN UNIQUE ( usuario_id , missao_id ) ;

CREATE TABLE TB_VIAGEM 
    ( 
     viagem_id           INTEGER  NOT NULL , 
     data_viagem         DATE  NOT NULL , 
     origem              VARCHAR2 (250)  NOT NULL , 
     destino             VARCHAR2 (250)  NOT NULL , 
     tipo_veiculo        VARCHAR2 (50)  NOT NULL , 
     km_percorrido       NUMBER (4,3)  NOT NULL , 
     carbono_emitido     NUMBER (6,2)  NOT NULL , 
     carbono_economizado NUMBER (6,2)  NOT NULL , 
     usuario_id          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_VIAGEM 
    ADD 
    CHECK (tipo_veiculo IN ('bicicleta', 'carro', 'metro', 'moto', 'onibus', 'trem')) 
;

ALTER TABLE TB_VIAGEM 
    ADD CONSTRAINT TB_VIAGEM_PK PRIMARY KEY ( viagem_id ) ;

ALTER TABLE TB_CARTEIRA 
    ADD CONSTRAINT TB_CARTEIRA_USUARIO_FK FOREIGN KEY 
    ( 
     usuario_id
    ) 
    REFERENCES TB_USUARIO 
    ( 
     usuario_id
    ) 
;

ALTER TABLE TB_COMPROVANTE 
    ADD CONSTRAINT TB_COMPROVANTE_USU_MIS_FK FOREIGN KEY 
    ( 
     usuario_id,
     missao_id
    ) 
    REFERENCES TB_USUARIO_MISSAO 
    ( 
     usuario_id,
     missao_id
    ) 
;

ALTER TABLE TB_PONTOS 
    ADD CONSTRAINT TB_PONTOS_USUARIO_FK FOREIGN KEY 
    ( 
     usuario_id
    ) 
    REFERENCES TB_USUARIO 
    ( 
     usuario_id
    ) 
;

ALTER TABLE TB_RECARGA 
    ADD CONSTRAINT TB_RECARGA_USUARIO_FK FOREIGN KEY 
    ( 
     usuario_id
    ) 
    REFERENCES TB_USUARIO 
    ( 
     usuario_id
    ) 
;

ALTER TABLE TB_USUARIO_CONQUISTA 
    ADD CONSTRAINT TB_USUARIO_CONQUISTA_CON_FK FOREIGN KEY 
    ( 
     conquista_id
    ) 
    REFERENCES TB_CONQUISTA 
    ( 
     conquista_id
    ) 
;

ALTER TABLE TB_USUARIO_CONQUISTA 
    ADD CONSTRAINT TB_USUARIO_CONQUISTA_USU_FK FOREIGN KEY 
    ( 
     usuario_id
    ) 
    REFERENCES TB_USUARIO 
    ( 
     usuario_id
    ) 
;

ALTER TABLE TB_USUARIO_MISSAO 
    ADD CONSTRAINT TB_USUARIO_MISSAO_MIS_FK FOREIGN KEY 
    ( 
     missao_id
    ) 
    REFERENCES TB_MISSAO 
    ( 
     missao_id
    ) 
;

ALTER TABLE TB_USUARIO_MISSAO 
    ADD CONSTRAINT TB_USUARIO_MISSAO_USU_FK FOREIGN KEY 
    ( 
     usuario_id
    ) 
    REFERENCES TB_USUARIO 
    ( 
     usuario_id
    ) 
;

ALTER TABLE TB_VIAGEM 
    ADD CONSTRAINT TB_VIAGEM_USUARIO_FK FOREIGN KEY 
    ( 
     usuario_id
    ) 
    REFERENCES TB_USUARIO 
    ( 
     usuario_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
